// libs/core/src/components/badge/badge.component.tsx
import { Component, ComponentInterface, h, Host, Prop } from '@stencil/core';

import { ThemeColor } from '../../helpers/theme-color.type';
@Component({
  tag: 'kirby-badge',
  styleUrl: 'badge.component.scss',
  shadow: true,
})
// tslint:disable-next-line: component-class-suffix
export class Badge implements ComponentInterface {
  @Prop() text: string;
  @Prop() themeColor: ThemeColor;

  render() {
    return (
      <Host class={this.themeColor}>
        <ion-badge>{this.text ? <span>{this.text}</span> : <slot />}</ion-badge>
      </Host>
    );
  }
}

// src/kirby/components/badge/badge.component.ts
import { Component, Input } from '@angular/core';

import { ThemeColor } from '../../helpers/theme-color.type';

@Component({
  selector: 'kirby-badge',
  templateUrl: './badge.component.html',
  styleUrls: ['./badge.component.scss'],
  // Using host property decorator is fine for static values:
  // tslint:disable-next-line:use-host-property-decorator
  host: {
    class: 'kirby-badge',
  },
})
export class BadgeComponent {
  @Input() themeColor: ThemeColor;
  @Input() text: string;
}

<ion-badge mode="ios" color="colortype">
  <ng-content *ngIf="!text"></ng-content>
  <ng-container *ngIf="text">{{text}}</ng-container>
</ion-badge>
